"""product variants

Revision ID: 0158e866d79d
Revises: 1cfaf9ab633b
Create Date: 2026-09-08 23:04:55.900191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0158e866d79d'
down_revision: Union[str, Sequence[str], None] = '1cfaf9ab633b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price_adjustment', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    op.add_column('cart_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'variants', ['variant_id'], ['id'])
    op.add_column('order_items', sa.Column('variant_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'variant_name')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'variant_id')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.drop_table('variants')
    # ### end Alembic commands ###
