"""guest checkout

Revision ID: 177a12a4660f
Revises: 87986fd0296b
Create Date: 2026-09-07 14:30:11.838255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177a12a4660f'
down_revision: Union[str, Sequence[str], None] = '87986fd0296b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('guest_name', sa.String(length=100), nullable=True))
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('addresses', 'guest_name')
    op.drop_column('addresses', 'guest_email')
    # ### end Alembic commands ###
