"""add is_featured to promo_codes and create home_sections

Revision ID: 5a29e8a475e3
Revises: 4c31d58918bf
Create Date: 2026-09-16 14:43:18.966695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a29e8a475e3'
down_revision: Union[str, Sequence[str], None] = '4c31d58918bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('section_type', sa.Enum('NEWEST', 'SILVER', 'CATEGORY', 'TAG', 'MANUAL', name='homesectiontype'), nullable=False),
    sa.Column('filter_value', sa.String(length=100), nullable=True),
    sa.Column('view_all_href', sa.String(length=255), nullable=False),
    sa.Column('display_limit', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_sections_id'), 'home_sections', ['id'], unique=False)
    op.add_column('promo_codes', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'is_featured')
    op.drop_index(op.f('ix_home_sections_id'), table_name='home_sections')
    op.drop_table('home_sections')
    # ### end Alembic commands ###
