"""shipping and stock reservation


Revision ID: 5f5678d344ee
Revises: 177a12a4660f
Create Date: 2026-09-07 22:13:19.055187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5678d344ee'
down_revision: Union[str, Sequence[str], None] = '177a12a4660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_city'), 'shipping_rates', ['city'], unique=True)
    op.create_index(op.f('ix_shipping_rates_id'), 'shipping_rates', ['id'], unique=False)
    op.add_column('orders', sa.Column('reserved_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reserved_until')
    op.drop_index(op.f('ix_shipping_rates_id'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_city'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
