"""footer model

Revision ID: e7e4218f1874
Revises: db2be8f2da73
Create Date: 2026-09-16 16:41:22.724769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e4218f1874'
down_revision: Union[str, Sequence[str], None] = 'db2be8f2da73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footer_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_sections_id'), 'footer_sections', ['id'], unique=False)
    op.create_table('site_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('copyright_text', sa.String(length=255), nullable=True),
    sa.Column('enamad_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_info_id'), 'site_info', ['id'], unique=False)
    op.create_table('footer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['footer_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_links_id'), 'footer_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_footer_links_id'), table_name='footer_links')
    op.drop_table('footer_links')
    op.drop_index(op.f('ix_site_info_id'), table_name='site_info')
    op.drop_table('site_info')
    op.drop_index(op.f('ix_footer_sections_id'), table_name='footer_sections')
    op.drop_table('footer_sections')
    # ### end Alembic commands ###
